python3 random_walks.py PL 0 &
python3 random_walks.py PL 1 &
python3 random_walks.py PL 2 &
python3 random_walks.py PL 3 &
python3 random_walks.py PL 4 &
python3 random_walks.py PL 5 &
python3 random_walks.py PL 6 &
python3 random_walks.py PL 7 &
python3 random_walks.py PL 8a &
python3 random_walks.py PL 8b &
python3 random_walks.py PL 8c &
python3 random_walks.py PL 8d &
python3 random_walks.py PL 8e &
python3 random_walks.py PL 8f &
python3 random_walks.py PL 8g &
python3 random_walks.py PL 9 &
python3 random_walks.py ALL 1 &
python3 random_walks.py ALL 2 &
python3 random_walks.py ALL 3 &
python3 random_walks.py ALL 4 &
python3 random_walks.py ALL 5 &
python3 random_walks.py ALL 6 &
python3 random_walks.py ALL 7 &
python3 random_walks.py ALL 8a &
python3 random_walks.py ALL 8b &
python3 random_walks.py ALL 8c &
python3 random_walks.py ALL 8d &
python3 random_walks.py ALL 8e &
python3 random_walks.py ALL 8f &
python3 random_walks.py ALL 8g &
python3 random_walks.py ALL 8h &
python3 random_walks.py ALL 9 
